name: Dotnet

on:
  push:
    pull_request: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test test/PackZero.Configuration.Tests/PackZero.Configuration.Tests.csproj --no-build --verbosity normal

    - name: publish
      id: PackZero_Configuration
      uses: alirezanet/publish-nuget@v3.0.3
      with:
          PROJECT_FILE_PATH: src/PackZero.Configuration/PackZero.Configuration.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}
